version: 0.2

env:
  runtime-versions:
    java: corretto17

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 314968779514.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=314968779514.dkr.ecr.us-east-1.amazonaws.com/aws-devops-springboot-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7 || echo latest)

  build:
    commands:
      - echo Building Spring Boot application...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"springboot-task","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
